--BORRADO DE TABLAS
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP TABLE GENEROS CASCADE CONSTRAINTS;
DROP TABLE GENERO_PELICULAS CASCADE CONSTRAINTS;
DROP TABLE PELICULAS CASCADE CONSTRAINTS;
DROP TABLE ACTOR CASCADE CONSTRAINTS;
DROP TABLE REPARTO CASCADE CONSTRAINTS;
DROP TABLE PALABRAS_CLAVE CASCADE CONSTRAINTS;
DROP TABLE PALABRAS_CLAVE_PELICULAS CASCADE CONSTRAINTS;
DROP TABLE CLUB CASCADE CONSTRAINTS;
DROP TABLE MIEMBROS CASCADE CONSTRAINTS;
DROP TABLE PELICULAS_PROPUESTAS CASCADE CONSTRAINTS;
DROP TABLE INVITACIONES CASCADE CONSTRAINTS;
DROP TABLE SOLICITUDES CASCADE CONSTRAINTS;
--DROP TABLE ACEPTACIONES CASCADE CONSTRAINTS;
DROP TABLE TIPO_CONTRATO CASCADE CONSTRAINTS;
DROP TABLE CONTRATOS CASCADE CONSTRAINTS;
DROP TABLE CESES CASCADE CONSTRAINT;
DROP TABLE CLUBES_HISTORICOS CASCADE CONSTRAINTS;
DROP TABLE IDBM CASCADE CONSTRAINT;



